<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <LangVersion>9</LangVersion>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);0169;0414;0649</NoWarn>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>portable</DebugType>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.Contains('TextMeshPro')) or $(MSBuildProjectName.Contains('AssetStore'))">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

</Project>
